// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTDqwQE0C2X0ToVRgrG_LFQaydLwA52M',
    appId: '1:183147970144:web:2032fac01cefa6a6828d05',
    messagingSenderId: '183147970144',
    projectId: 'salonconnect-indb2d-2025',
    authDomain: 'salonconnect-indb2d-2025.firebaseapp.com',
    storageBucket: 'salonconnect-indb2d-2025.firebasestorage.app',
    measurementId: 'G-TM3HXQ8YEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJGl8rNbAhEhugv0LFY5GkoIMwqwGUiY',
    appId: '1:183147970144:android:2b76d7ef62315cd8828d05',
    messagingSenderId: '183147970144',
    projectId: 'salonconnect-indb2d-2025',
    storageBucket: 'salonconnect-indb2d-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsVSFkuBGiUtPI0b7Yy_TRDdSctm_NeQc',
    appId: '1:183147970144:ios:ace033fdfadcd854828d05',
    messagingSenderId: '183147970144',
    projectId: 'salonconnect-indb2d-2025',
    storageBucket: 'salonconnect-indb2d-2025.firebasestorage.app',
    iosBundleId: 'com.example.salonConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsVSFkuBGiUtPI0b7Yy_TRDdSctm_NeQc',
    appId: '1:183147970144:ios:ace033fdfadcd854828d05',
    messagingSenderId: '183147970144',
    projectId: 'salonconnect-indb2d-2025',
    storageBucket: 'salonconnect-indb2d-2025.firebasestorage.app',
    iosBundleId: 'com.example.salonConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChTDqwQE0C2X0ToVRgrG_LFQaydLwA52M',
    appId: '1:183147970144:web:1f8574c6574cbcd8828d05',
    messagingSenderId: '183147970144',
    projectId: 'salonconnect-indb2d-2025',
    authDomain: 'salonconnect-indb2d-2025.firebaseapp.com',
    storageBucket: 'salonconnect-indb2d-2025.firebasestorage.app',
    measurementId: 'G-D9YJ6Q7X73',
  );
}
